porterhq/porter

import.js
index.js
test/test.compileAll.js
test/test.compileComponent.js
test/test.compileModule.js
test/test.compileStyleSheets.js

1. should resolve dependencies even if error occured
2. should not yield next if current request can be handled
3. should add a `MODULE_FETCHING` status to prevent duplicated requests

Fix: issues found after refactoring of 4.1.0 (fixes #13)

---

.travis.yml
lib/Cache.js

so let's change from spawn bin/compileModule.js directly to spawn node
and pass bin/compileModule.js as the argument instead.

Fix: --harmony in shebang does not work on linux

---

.travis.yml
bin/compileModule.js
index.js
lib/Cache.js
lib/compileAll.js
lib/compileStyleSheets.js
lib/deheredoc.js
lib/findComponent.js
lib/findModule.js
lib/fs.js
lib/glob.js
lib/mkdirp.js
lib/parseMap.js
package.json
test/example/components/stylesheets/app.css
test/test.index.js

在 middleware 中处理掉 `@import` 逻辑，从而允许模块 `@import` 自身依赖的模块的 CSS

Fix: @import at server side for proper import logic

---

History.md
packages/porter/src/package.js

ref: https://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener

fix: turn off recursive fs.watch if platform is linux

---

packages/porter/src/module.js

修复 baseURL 为远程时没有child.family导致的错误

---

packages/porter/src/module.js
packages/porter/src/package.js

refactor: trying to simplify mod.family iterator

---

packages/porter/src/package.js

bundle 文件在编译的时候 ，使用内容进行 md5 ，并重写 entry

feat: calculate bundle by content

---

packages/porter/src/package.js
packages/porter/src/porter.js

fix: `require('./')` & source map of node_modules from npminstall

---

packages/porter/package.json

https://github.com/erzu/porter/security/dependabot/packages/porter/package.json/postcss/open

upgrade: postcss >= 8.2.10

---

.github/workflows/node.js.yml
.gitignore
.travis.yml
package.json
packages/demo-app/package.json
packages/demo-postcss/package.json
packages/demo-proxy/package.json
packages/porter-cli/package.json
packages/porter/package.json

build: github actions & codecov

---

packages/demo-app/components/cyclic-dep/foo.js
packages/demo-app/components/home.js
packages/porter/src/packet.js
packages/porter/test/unit/module.test.js
packages/porter/test/unit/packet.test.js

fix: reloading cyclic module should not cause dead loop

---

.github/workflows/node.js.yml
History.md
lerna.json
packages/demo-app/package.json
packages/demo-cli/package.json
packages/demo-component/package.json
packages/demo-postcss/package.json
packages/demo-proxy/package.json
packages/demo-typescript/package.json
packages/demo-wasm/package.json
packages/demo-worker/package.json
packages/porter-cli/package.json
packages/porter/package.json
packages/porter/src/bundle.js
packages/porter/src/porter.js
packages/porter/test/unit/bundle.test.js

Merge v3.x

---

packages/demo-app/components/stylesheets/common/base.css
packages/porter-cli/package.json
packages/porter/package.json
packages/porter/src/bundle.js
packages/porter/src/js_module.js
packages/porter/src/packet.js
packages/porter/src/porter.js
packages/porter/test/integration/porter.test.js
packages/porter/test/integration/porter_preload.test.js
packages/porter/test/unit/bundle.test.js
packages/porter/test/unit/js_module.test.js
packages/porter/test/unit/packet.test.js

fix: source mapping url in bundle results & cache paths

---

packages/porter/src/bundle.js
packages/porter/src/packet.js
packages/porter/src/porter.js
packages/porter/test/integration/porter.test.js

fix: all of the lazyloaded entries and dependencies should be compiled

---

packages/demo-app/components/lazyload.js
packages/demo-app/components/lazyload_dep.js
packages/porter/package.json
packages/porter/src/bundle.js
packages/porter/src/packet.js
packages/porter/src/porter.js
packages/porter/test/unit/bundle.test.js
packages/porter/test/unit/compile_all.test.js

fix: isolated packets will have their dependencies bundled together

---

packages/porter/src/bundle.js
packages/porter/test/unit/bundle.test.js

fix: isolated packages should have their dependencies bundled together

---

packages/porter/src/bundle.js
packages/porter/src/css_module.js
packages/porter/src/fake_packet.js
packages/porter/src/js_module.js
packages/porter/src/module.js
packages/porter/src/packet.js
packages/porter/src/porter.js
packages/porter/src/ts_module.js
packages/porter/test/integration/porter.test.js
packages/porter/test/integration/porter_isolate.test.js
packages/porter/test/integration/porter_preload.test.js
packages/porter/test/unit/bundle.test.js
packages/porter/test/unit/compile_all.test.js
packages/porter/test/unit/compile_entry.test.js
packages/porter/test/unit/css_module.test.js
packages/porter/test/unit/fake_packet.test.js
packages/porter/test/unit/js_module.test.js
packages/porter/test/unit/json_module.test.js
packages/porter/test/unit/module.test.js
packages/porter/test/unit/packet.test.js
packages/porter/test/unit/ts_module.test.js
packages/porter/test/unit/wasm_module.test.js

porter.package -> porter.packet
mod.package -> mod.packet

refactor: package -> packet

---

packages/porter/src/bundle.js

temporary fix for dependencies that have css in js

fix: css modules should not be bundled in js bundle

---

packages/demo-css-in-js/components/.eslintrc
packages/demo-css-in-js/components/home.js
packages/demo-css-in-js/components/home_dep.js
packages/demo-css-in-js/components/stylesheets/app.css
packages/demo-css-in-js/package.json
packages/porter/loader.js
packages/porter/src/at_import.js
packages/porter/src/bundle.js
packages/porter/src/css_module.js
packages/porter/src/js_module.js
packages/porter/src/named_import.js
packages/porter/src/packet.js
packages/porter/src/porter.js
packages/porter/src/ts_module.js
packages/porter/test/unit/at_import.test.js
packages/porter/test/unit/babel_plugin.test.js
packages/porter/test/unit/bundle.test.js
packages/porter/test/unit/css_module.test.js
packages/porter/test/unit/js_module.test.js
packages/porter/test/unit/named_import.test.js

fixes #71, along with a over simplified babel-plugin-import parody

feat: support requiring css in js modules

---

packages/porter/src/packet.js

fix: possible TypeError in packet.compile()

---

packages/porter/src/js_module.js
packages/porter/src/module.js
packages/porter/src/packet.js

fix: ignore dts imports in module dependencies

---

packages/porter/src/porter.js
packages/porter/test/unit/compile_all.test.js

fix: excluded packets should be compiled when compileAll

---

packages/demo-app/components/home.js
packages/porter/src/packet.js
packages/porter/test/unit/packet.test.js

fix: should drop the './' prefix when normalize file

---

packages/demo-app/browser_modules/require-directory/suite.js
packages/porter/src/packet.js

fix: should make sure folder specifiers are correctly marked

---

packages/porter/src/bundle.js
packages/porter/src/js_module.js
packages/porter/src/porter.js
packages/porter/test/unit/bundle.test.js

also restored porter.parseId perf and several debug output for problem identification

fix: bundle scope on lazyloaded modules

---

packages/porter/src/packet.js
packages/porter/test/integration/porter_preload.test.js

css module changes in dependencies should trigger root bundle reload too, if the css module were required.
fixes #98

fix: reload bundles at both root and dependency levels

---

.eslintrc
packages/porter/src/cache.js
packages/porter/src/js_module.js
packages/porter/src/module.js
packages/porter/src/packet.js
packages/porter/src/porter.js
packages/porter/test/unit/cache.test.js

by integrating etag as hash salt

refactor: extract app.cache as isolated class and replace etag check

---

packages/porter/src/packet.js
packages/porter/src/porter.js
packages/porter/src/stub.js

chore: stub debug log

---

packages/porter/src/porter.js

fix: compileEntry() should wait until instance is ready

---

packages/demo-app/components/lazyload.js
packages/porter/src/packet.js
packages/porter/src/porter.js
packages/porter/test/integration/porter_lazyload.test.js

fix: lazyloaded dependencies should be manifested

---

packages/porter/src/bundle.js

to keep from obtaining redundantly such as:
```
porter bundle start assets/css/app.css .css [ 'assets/css/app.css' ] +31s
porter bundle start assets/css/app.css .css [ 'assets/css/app.css' ] +0ms
porter bundle start assets/css/app.css .css [ 'assets/css/app.css' ] +1s
porter bundle start assets/css/app.css .css [ 'assets/css/app.css' ] +1ms
```

refactor: throttle bundle.obtain() calls

---

packages/porter/src/bundle.js
packages/porter/src/porter.js

all of the dependencies shall be compiled as separate bundles

fix: traverse lazyloaded dependencies

---

packages/porter/src/porter.js

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified

fix: 'Last-Modified' accepts ascii string only

---

packages/porter/src/fake_packet.js
packages/porter/src/module.js
packages/porter/test/unit/fake_packet.test.js

fix: should still prefer custom loaderConfig in proxy mode

---

packages/porter/src/named_import.js
packages/porter/test/unit/named_import.test.js

fix: require('antd/lib/button').default

---

packages/porter/loader.js
packages/porter/src/porter.js

fix: problems caused by .[contenthash].wasm

---

packages/demo-app/browser_modules/require-json/suite.js
packages/porter/loader.js
packages/porter/src/bundle.js
packages/porter/test/unit/bundle.test.js

there will always be default bundles for dependencies

fix: import "dependency/foo.json" should be bundled as well

---

packages/porter/loader.js

fix: const not allowed in strict mode Chrome 40

---

packages/porter/loader.js

fix: should always fallback to WebAssembly.instantiate(arrayBuffer)

---

packages/demo-app/browser_modules/test/suite.js
packages/porter/loader.js
packages/porter/src/js_module.js
packages/porter/src/module.js
packages/porter/test/unit/module.test.js

fix: support import(specifier): Promise<exports>

---

packages/demo-app/browser_modules/test/suite.js
packages/porter/loader.js
packages/porter/src/packet.js
packages/porter/src/porter.js

fix: import(unknown) should not trigger bundle request

---

packages/porter/src/module.js

fix: fake modules might not have dynamicImports initialized

---

packages/demo-app/browser_modules/dynamic-import/suite.js
packages/demo-app/browser_modules/dynamic-import/sum.js
packages/demo-app/browser_modules/test/suite.js
packages/demo-app/components/home_dep.css
packages/porter/src/bundle.js
packages/porter/src/js_module.js
packages/porter/src/module.js
packages/porter/src/packet.js
packages/porter/src/porter.js
packages/porter/test/unit/bundle.test.js
packages/porter/test/unit/compile_all.test.js
packages/porter/test/unit/js_module.test.js
packages/porter/test/unit/module.test.js

fix: import(arbitrary module)

---

packages/porter/src/bundle.js
packages/porter/test/unit/bundle.test.js
packages/porter/test/unit/compile_all.test.js
packages/porter/test/unit/packet.test.js

... should include css modules from both entries

fix: compiling css bundle with same name js entry

---

packages/porter/src/js_module.js
packages/porter/src/module.js
packages/porter/src/packet.js
packages/porter/test/unit/compile_entry.test.js

fix: compile fake entries should not cut imports

---

packages/porter/loader.js

fix: fallback to response.arrayBuffer() to cope with baxia script

---

packages/porter/loader.js

requestWasm 里面 fetch 的 catch 没有被 callback

fix: add error callback for loadWasm

---

.github/workflows/node.js.yml
History.md
Readme.md
docs/Gemfile
packages/porter/Readme.md

chore: remove obsolete documentation & start testing against node v18

---

packages/demo-complex/app/web/test/foo.jsx
packages/demo-complex/app/web/test/suite.js
packages/porter/src/module.js

fix: import('./foo.jsx')

---

packages/porter/src/packet.js
packages/porter/test/unit/compile_all.test.js
packages/porter/test/unit/packet.test.js

feat: support options.source.mappingURL

---

.github/workflows/node.js.yml
packages/porter-cli/bin/porter-serve.js
packages/porter-cli/package.json

refactor(porter-cli): switch to puppeteer-core

---

packages/porter/src/js_module.js

fix: custom uglify options should be passed on

---

packages/porter/src/js_module.js

fix: app.uglifyOptions should not be overwritten

---

packages/porter/src/packet.js

fix: lazyload css should present in packet.manifest

---

packages/porter/loader.js

fix: loader.js still needs to be `const` free

---

.github/workflows/node.js.yml
packages/demo-complex/app/web/about.jsx
packages/demo-complex/app/web/about_dep.js
packages/demo-complex/app/web/about_dep.scss
packages/demo-complex/package.json
packages/porter/src/sass_module.js
packages/porter/test/complex/index.test.js
packages/porter/test/unit/sass_module.test.js

fix: @import "packet/file.scss" in sass modules

---

packages/demo-complex/app/web/home.jsx
packages/porter/src/bundle.js
packages/porter/src/module.js
packages/porter/src/packet.js
packages/porter/test/complex/index.test.js
packages/porter/test/unit/compile_entry.test.js

fix: import('other/root/entry') should be manifested

---

packages/porter/src/packet.js

chore: reset moduleCache[fpath] only once

---

.github/workflows/node.js.yml
packages/porter/loader.js
packages/porter/src/babel_plugin.js
packages/porter/src/packet.js
packages/porter/test/unit/babel_plugin.test.js

- https://vitejs.dev/guide/features.html#glob-import

feat: support glob import

---

.gitignore
docs/_layouts/en.html
docs/_layouts/zh.html
docs/contributing/guides.md
docs/design.md
docs/dynamic-import.md
docs/options.md
docs/wasm.md
docs/zh/options.md
packages/porter/Readme.md

- move legacy contents into archive secion in docs
- add /zh/options

docs: update packages/porter/Readme.md

---

Readme.md
Readme.zh-CN.md
docs/zh/options.md
packages/porter/Readme.zh-CN.md

docs: 添加仓库的和 @cara/porter 包的中文 Readme

---

docs/assets/css/style.scss
docs/zh/modules.md
docs/zh/options.md
packages/porter/src/cache.js
packages/porter/src/porter.js
packages/porter/test/unit/bundle.test.js
packages/porter/test/unit/cache.test.js
packages/porter/test/unit/compile_all.test.js
packages/porter/test/unit/css_module.test.js
packages/porter/test/unit/js_module.test.js
packages/porter/test/unit/json_module.test.js
packages/porter/test/unit/packet.test.js
packages/porter/test/unit/sass_module.test.js
packages/porter/test/unit/wasm_module.test.js

feat: support cache.clean and output.clean

---

packages/porter/src/bundle.js
packages/porter/src/js_module.js
packages/porter/src/ts_module.js
packages/porter/test/unit/sass_module.test.js
packages/porter/test/unit/ts_module.test.js

make sure descendants are bundled before ancestors

refactor: simplify bundle iterate order

---

packages/porter/src/bundle.js
packages/porter/test/app/index.test.js
packages/porter/test/unit/compile_all.test.js

fix: css entries order matters and should not be tampered

---

packages/demo-app/browser_modules/test/suite.js
packages/demo-app/package.json
packages/porter/src/js_module.js
packages/porter/src/match_require.js
packages/porter/src/module.js
packages/porter/test/app/index.test.js

fix: dependencies in es module format should be transpiled automatically

---

.github/workflows/node.js.yml
docs/zh/contributing/guides.md
package.json
packages/demo-component/package.json
packages/porter-cli/components/runner.js
packages/porter-cli/public/runner.html
packages/porter-cli/test/porter-serve.test.js
packages/porter/src/bundle.js
packages/porter/src/packet.js
packages/porter/src/porter.js
packages/porter/test/app/index.test.js
packages/porter/test/complex/index.test.js
packages/porter/test/integration/porter.test.js
packages/porter/test/typescript/index.test.js
packages/porter/test/unit/bundle.test.js
packages/porter/test/unit/css_module.test.js
packages/porter/test/unit/js_module.test.js
packages/porter/test/unit/module.test.js
packages/porter/test/unit/sass_module.test.js
run-script.sh

- https://docs.npmjs.com/cli/v8/using-npm/workspaces
- https://github.com/npm/rfcs/issues/575

refactor: replace lerna with npm workspaces

---

packages/demo-wasm/components/test/.eslintrc
packages/demo-wasm/components/test/bundler.js
packages/demo-wasm/components/test/missing_wasm/index.js
packages/demo-wasm/components/test/missing_wasm/index_bg.js
packages/demo-wasm/components/test/suite.js
packages/demo-wasm/components/test/web.js
packages/demo-wasm/package.json
packages/porter/loader.js

try to display diagnostic messages when ignition timeout

fix: exceptions thrown during wasm loading should bubble up

---

packages/demo-app/browser_modules/import-meta/.eslintrc
packages/demo-app/browser_modules/import-meta/suite.js
packages/demo-app/browser_modules/test/suite.js
packages/porter/loader.js
packages/porter/src/babel_plugin.js
packages/porter/test/unit/babel_plugin.test.js

feat: support import.meta.resolve()

---

docs/_layouts/en.html
docs/assets/css/style.scss

docs: header style in dark mode with small viewport

---

packages/porter/src/ts_module.js
packages/porter/test/unit/ts_module.test.js

fix: ts module source map

---

packages/porter/loader.js

make sure these urls can be matched and deduplicated when importing css entry
```html
<link ref="stylesheet" href="/foo/bar.css">
<script src="/foo/bar.js"></script>
```
with following /foo/bar.js
```js
import './style.css';
```
which will try to request `/foo/bar.[contenthash].css` by default, and should be skipped if `/foo/bar.[contenthash].css` or `/foo/bar.css` were loaded already.

fix: local environment have different style urls

---

packages/porter/src/packet.js
packages/porter/test/fixtures/demo-package-babel-config-cjs/babel.config.cjs
packages/porter/test/fixtures/demo-package-babel-config-cjs/package.json
packages/porter/test/unit/packet.test.js

fix: should be able to handle babel.config.cjs

---

packages/porter/src/css_module.ts
packages/porter/test/unit/css_module.test.js

fix: @import url() in css modules

---

examples/app/lib/exclude.js
packages/porter/.gitignore
packages/porter/.npmignore
packages/porter/defs/loader.d.ts
packages/porter/index.d.ts
packages/porter/package.json
packages/porter/src/bundle.ts
packages/porter/src/css_module.ts
packages/porter/src/defs/index.d.ts
packages/porter/src/packet.ts
packages/porter/test/unit/css_module.test.js
packages/porter/tsconfig.json

feat: emit declaration files and export with types

---

packages/porter/package.json
packages/porter/src/css_module.ts
packages/swc-plugin-deheredoc/Cargo.toml
packages/swc-plugin-deheredoc/src/deheredoc.rs
packages/swc-plugin-glob-import/Cargo.toml
packages/swc-plugin-glob-import/src/lib.rs
packages/swc-plugin-porter/Cargo.toml

@swc/core should have its version locked because plugin backword compatibility is not guaranteed
- https://swc.rs/docs/plugin/selecting-swc-core

chore: upgrade swc_core@0.69.*

---

examples/component/test/.eslintrc
examples/component/test/add.js
examples/component/test/suite.js
packages/porter/src/js_module.ts
packages/porter/src/packet.ts
packages/swc-plugin-deheredoc/Cargo.toml
packages/swc-plugin-glob-import/Cargo.toml
packages/swc-plugin-porter/Cargo.toml

fix: fallback to swc if no transpiler were found

---

Readme.zh-CN.md
docs/CNAME
docs/_layouts/en.html
docs/_layouts/zh.html
docs/assets/css/style.scss
docs/cli.md
docs/modules.md
docs/options.md
docs/packets.md
docs/swc.md
docs/wasm.md
docs/zh/modules.md
docs/zh/starter.md
docs/zh/swc.md

docs: en documentations; overview of the migration to SWC

---

packages/porter/package.json
packages/porter/src/bundle.ts
packages/porter/src/css_module.ts
packages/porter/src/module.ts
packages/porter/src/packet.ts
packages/swc-plugin-deheredoc/Cargo.toml
packages/swc-plugin-glob-import/Cargo.toml
packages/swc-plugin-porter/Cargo.toml

fix: handle css bundles first to generate css module exports

---

packages/porter/src/css_module.ts
packages/porter/src/json_module.ts

fix: css module exports were referencing wrong var

---

packages/porter/src/css_module.ts

fix: css module exports need to be handled at compile phase as well

---

.eslintrc
package.json
packages/porter/src/import_visitor.ts
packages/porter/test/unit/import_visitor.test.ts

fix: ImportVisitor incorrectly excludes ts imports

---

packages/porter/package.json
packages/swc-plugin-deheredoc/Cargo.toml
packages/swc-plugin-glob-import/Cargo.toml
packages/swc-plugin-porter/Cargo.toml

<https://swc.rs/docs/plugin/selecting-swc-core#v078x>
```
Caused by:
Syntax Error (node_modules/_jimp@0.22.8@jimp/browser/lib/jimp.js)
at Object.parseSync (<anonymous>)
```

deps: upgrade swc_core for jimp fix

---

packages/swc-plugin-deheredoc/Cargo.toml

chore: remove unused dev dep

---

.github/workflows/node.js.yml
.github/workflows/npmpublish.yml
packages/porter/package.json
packages/porter/src/css_module.ts
packages/swc-plugin-deheredoc/Cargo.toml
packages/swc-plugin-glob-import/Cargo.toml
packages/swc-plugin-porter/Cargo.toml

https://lightningcss.dev/docs.html

deps: upgrade to lightningcss
