lib/compileAll.js

读源码的时候，照着注释里面的 `compileAll({ base: './componets', match: 'ma/*' })` 拷出来，贴到本地仓库，结果没编译出结果，对比下，发现 componets 的单词误拼写了

Correct componets to components

---

.eslintrc
import.js
test/example/components/main.js

There are cases at browser side that require modules asynchronously.
给模块加上了 `.on`、`.emit` 套装，方便回调。

Add: require.async support

---

index.js
lib/compileAll.js
lib/parseMap.js
test/example/browser_modules/v2/main.js
test/test.compileAll.js

Allow `opts.base` to be an array in oceanify factory and compilation helpers. e.g.
```js
app.use(oceanify({ base: ['browser_modules', 'components'] }))
oceanify.compileAll({ base: ['browser_modules', 'components'] })
oceanify.compileComponent('foo', { base: ['browser_modules', 'components'] })
```
This enables richer infrastructures.

Support multiple bases

---

.travis.yml
Readme.md
Readme.zh.md
bin/compileModule.js
index.js
lib/Cache.js
lib/compileAll.js
lib/compileStyleSheets.js
lib/findComponent.js
lib/glob.js
lib/parseMap.js
loader.js
package.json
test/command/test.compileModule.js
test/example-fe/app.js
test/example/app.js
test/test.compileAll.js
test/test.index.js
test/test.parseMap.js
test/test.serveSelf.js
test/test.serveSource.js

- 去掉 Node.js 4 支持
- 修改 opts.base 为 opts.paths 以体现支持多个 components 目录的特性
- opts.importConfig 改为 opts.loaderConfig
- 增加 opts.loaderConfig.preload
- 完善 opts.loaderConfig.map，减少需要写正则的场景
- opts.self 改为 opts.serveSelf
- 支持传入 opts.dependenciesMap 以使用 remote base
- 无论开发时还是编译时都合并 `@import`，以确保 node_modules 中的样式可以顺利引用，以及被 autoprefixer 处理
- 重命名 import.js 为 loader.js，更顾名思义一点

Breaking: Early import and map

---

index.js
package.json

Oceanify@5 introduces a lot of breaking changes. One of them is that the
components, both css and js, are now referenced with full path in the
format of `/${name}/${version}/${entry}`. This change makes versioning
of components possible.
The change itself is not backward compatible, which makes legacy
code hard to upgrade. Hence with this commit, we brought the good old
`/${entry}` reference of component back.
Be warned, the components still will be compiled into
`${dest}/${name}/${version}/` directory. This commit only brings the dev
behaviour back.

Fix: /component/entry should be supported still

---

packages/porter/package.json
packages/porter/src/porter.js

使用支持 postcss-preset-env ， 同时 postcss-set-env 自带 autoprefixer 所以无需在需要 autoprefixer

feat: use postcss-preset-env

---

packages/porter/loader.js

没有直接 delete，如果未来有需要可以 Object.keys(fetching).include(uri) 来判断曾经加载过，不过目前好像没啥用

模块下载执行完成后，标记 fetching

---

packages/porter/loader.js

• 跨域资源引用下，由于浏览器基于安全考虑故意隐藏了其它域JS文件抛出的具体错误信息，前端监控探针只会检测到一个 script error的异常。所以需要增加对于属性

chore: add crossorigin to script for error detection

---

packages/demo-app/.babelrc
packages/demo-app/browser_modules/test/suite.js
packages/demo-app/components/home_dep.js
packages/demo-app/package.json
packages/demo-worker/index.js
packages/porter-cli/test/porter-serve.test.js
packages/porter/loader.js
packages/porter/src/bundle.js
packages/porter/src/css_module.js
packages/porter/src/js_module.js
packages/porter/src/module.js
packages/porter/src/packet.js
packages/porter/src/porter.js
packages/porter/src/ts_module.js
packages/porter/test/integration/porter.test.js
packages/porter/test/integration/porter_preload.test.js
packages/porter/test/unit/bundle.test.js
packages/porter/test/unit/compile_all.test.js
packages/porter/test/unit/packet.test.js

```js
import Worker from 'worker-loader!@cara/demo-worker/components/worker.js';
```
Bundling strategy is changed a bit too, with worker entries ignoring preload settings and have all the dependencies bundled.

fix: loading web worker from dependencies & @babel/runtime issue

---

packages/demo-app/package.json
packages/porter/package.json
packages/porter/src/bundle.js
packages/porter/src/css_module.js
packages/porter/src/js_module.js
packages/porter/src/module.js
packages/porter/src/packet.js
packages/porter/src/porter.js
packages/porter/test/unit/css_module.test.js
packages/porter/test/unit/js_module.test.js

- sources should point to the correct paths relative to app.root
- replaced postcss-clean in the css transpiler test case because cssnano looks way more promising

fix: sources in source map generated by css and js transpiler

---

.github/workflows/node.js.yml
packages/porter/src/packet.js
packages/porter/src/porter.js
packages/porter/test/ts_module.test.js

when partial compiling, exclusive packages might not be loaded, which should be skipped.

fix: compilation output of ts entries should be `.js`

---

packages/porter/src/packet.js

fix: entry check should allow extensions like `.jsx` or `.tsx` too

---

packages/porter/package.json
packages/porter/src/porter.js

which might have its appearance order changed in actual postcss plugins

fix: drop the default autoprefixer & unused dependency

---

packages/porter/src/packet.js

register compiled bundles to packet.bundles, make sure duplicated bundles aren't created.

fix: manifest.json should map only the output

---

packages/porter/src/constants.js
packages/porter/src/css_module.js
packages/porter/src/js_module.js
packages/porter/src/module.js
packages/porter/src/packet.js
packages/porter/src/porter.js
packages/porter/test/integration/porter.test.js
packages/porter/test/unit/css_module.test.js
packages/porter/test/unit/js_module.test.js

for example, when requesting /entry.css and /entry.js simutaneously, and porter starts packing bundles for entry.css, entry.js might be added to porter.entries already but the module isn't fully parsed yet. It should be ignored, and left to the second packing iteration.
Otherwise the packed entry.js is incomplete

fix: porter.pack() should ignore incomplete modules

---

packages/porter/src/babel_plugin.js
packages/porter/src/json_module.js
packages/porter/src/packet.js
packages/porter/src/wasm_module.js
packages/porter/test/unit/babel_plugin.test.js
packages/porter/test/unit/json_module.test.js
packages/porter/test/unit/wasm_module.test.js

also fixed `packet.pack()`, when the packet takes too much time to parse, `packet.pack()` might be called earlier. In such case, a wait poll is necessary.

fix: require('heredoc').strip

---

packages/porter/src/packet.js
packages/porter/test/integration/porter_preload.test.js

because when options.preload is positive, the changes might need to be reflected in root bundles

fix: packet reload should take the change up to the root bundles

---

packages/demo-typescript/tsconfig.json
packages/porter/src/ts_module.js
packages/porter/test/unit/ts_module.test.js

otherwise sourceMapText would be undefined because it is inlined in transpile code already

fix: override inlineSourceMap option to force source map

---

packages/porter/src/css_module.js
packages/porter/test/unit/css_module.test.js

setting the intermediate source root to `/` shall suffice. The `options.source.root` will be set to the source map of bundle output afterwards.

fix: intermediate css source map should not have full sourceRoot

---

packages/porter/src/bundle.js
packages/porter/src/cache.js
packages/porter/src/js_module.js
packages/porter/src/module.js
packages/porter/src/packet.js
packages/porter/src/porter.js
packages/porter/test/integration/porter.test.js
packages/porter/test/integration/porter_lazyload.test.js
packages/porter/test/integration/porter_preload.test.js
packages/porter/test/unit/bundle.test.js
packages/porter/test/unit/compile_all.test.js
packages/porter/test/unit/compile_entry.test.js
packages/porter/test/unit/css_module.test.js
packages/porter/test/unit/fake_packet.test.js
packages/porter/test/unit/js_module.test.js
packages/porter/test/unit/json_module.test.js
packages/porter/test/unit/less_module.test.js
packages/porter/test/unit/module.test.js
packages/porter/test/unit/packet.test.js
packages/porter/test/unit/stub.test.js
packages/porter/test/unit/ts_module.test.js
packages/porter/test/unit/wasm_module.test.js

allow application to custom bundle existence checker with `options.bundle.exists(bundle)`. If not specified, will check against the output files at `options.output.path` instead.
`* bundle[Symbol.iterator]` is changed to always iterate entries in sorted order to make sure the bundle output is idempotent. 
`packet.lock` is now deprecated because the lock data might be intimidating (>= 40 KB uncompressed) in large applications. Further optimization would be compile away these lock data at transpile phase. For now, a more compact and consistent `module.lock` is used.
`module.lock` will now have the dependencies sorted to make sure the returned JSON object is idempotent across porter parsing passes.
Yet another change is making the `porter[get ready()]` into `porter.ready()` to pass pack …

feat: new Porter({ bundle: { async exists(bundle): boolean });

---

packages/demo-app/browser_modules/test/suite.js
packages/demo-app/package.json
packages/porter/src/cache.js
packages/porter/src/module.js
packages/porter/src/porter.js
packages/porter/test/unit/module.test.js

currently only `{ fs: false }` is added, which handles the unmet dependency warning of 'fs' in fontkit. Further use scenarios might include `{ path: 'path-browserify' }` etc.
- https://webpack.js.org/configuration/resolve/#resolvefallback

feat: options.resolve.fallback

---

packages/porter/src/named_import.js
packages/porter/test/unit/named_import.test.js

monolithic libraries like antd/lodash needs to be `require`d or `import`ed on demand for better perf

fix: named imports in cjs modules

---

packages/porter/src/bundle.js
packages/porter/test/unit/packet.test.js

there was a 60s~70s build perf regression in our app (260s -> 330s), skip the existence check if not specified and see if this is the cause

refactor: skip existence check if app.bundle.exists not specified

---

packages/porter/loader.js
packages/porter/src/packet.js

- web workers output paths should present in manifest
- wasm context modules might be defined twice, not sure how that happened exactly
- wasm output paths should be ready before compile the rest of the packet

fix: wasm/workercompilation minor issues

---

packages/demo-worker/components/test/suite.js
packages/demo-worker/package.json
packages/hello-worker/.eslintrc
packages/hello-worker/index.js
packages/hello-worker/package.json
packages/hello-worker/worker.js
packages/porter/loader.js

to better handle following scenarios:
- import app components without name/version prefix
- import dependencies with name/version prefix
- import workers in dependencies with name/version prefix, which means the entry module is prefixed as well
- import app components with name/version prefix, which is possible when writing library tests

refactor: simplify Module.resolve() in loader.js

---

packages/hello-worker/index.js
packages/hello-worker/worker.js
packages/porter/loader.js
packages/porter/src/bundle.js
packages/porter/src/porter.js
packages/porter/test/unit/bundle.test.js

for example, a.js -> require('worker-loader!./b.js'), two bundles should be generated:
- a.js (without b.js)
- b.js (as worker entry)

refactor: worker entries should not be bundled with initiators

---

packages/porter/loader.js

might be mapped as local module

fix: should skip uri parsing if mapped result starts with '/'

---

packages/porter/src/bundle.js
packages/porter/src/packet.js
packages/porter/test/unit/packet.test.js

- added tests covering the logic that the `.wasm` entries need to be put before other entries

refactor: reduce module check when packing packet

---

packages/demo-app/browser_modules/test/suite.js
packages/demo-app/components/dynamic_imports.js
packages/porter/src/css_module.js
packages/porter/src/js_module.js
packages/porter/src/less_module.js
packages/porter/src/match_require.js
packages/porter/src/module.js
packages/porter/src/packet.js
packages/porter/src/porter.js
packages/porter/test/unit/compile_entry.test.js
packages/porter/test/unit/js_module.test.js
packages/porter/test/unit/match_require.test.js
packages/porter/test/unit/packet.test.js

- refactor: replace glue code with options.resolve.fallback
- fixes existing usage like `require.async('some-package', exports => exports.default())`

fix: require.async() & partial support of `import()`

---

packages/demo-app/components/home.css
packages/demo-app/components/home_dep.js
packages/demo-complex/app/web/components/button.jsx
packages/demo-complex/app/web/home.jsx
packages/demo-complex/app/web/test/suite.js
packages/demo-complex/app/web/utils/string.mjs
packages/demo-complex/package.json
packages/porter/loader.js
packages/porter/src/bundle.js
packages/porter/src/js_module.js
packages/porter/src/module.js
packages/porter/src/packet.js
packages/porter/test/unit/bundle.test.js
packages/porter/test/unit/js_module.test.js
packages/porter/test/unit/less_module.test.js
packages/porter/test/unit/packet.test.js
packages/porter/test/unit/wasm_module.test.js

```js
import './foo.mjs';
import './foo.cjs';
import './bar'; // -> bar.jsx
import './baz'; // -> baz.tsx
// etc.
```
according to the standard, specifiers of es modules should include the file extension, hance the `.mjs` auto resolution is not added. also fixed a minor issue the when both js and css entries use the same filename, such as app.js and app.css, the js bundle might get wrong module resolution data.

fix: js extensions such as { .jsx, .mjs, .cjs }

---

packages/porter/loader.js

chrome 70 版本 import wasm 包时报错：TypeError: Failed to execute 'arrayBuffer' on 'Response': body stream is locked
According to MDN: https://developer.mozilla.org/en-US/docs/Web/API/Response/clone
> clone() throws a [TypeError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError) if the response body has already been used. In fact, the main reason clone() exists is to allow multiple uses of body objects (when they are one-use only.)
Related Q&A on stackoverflow.com:
https://stackoverflow.com/questions/53511974/javascript-fetch-failed-to-execute-json-on-response-body-stream-is-locked

fix: Response can only be consumed once in some lower version browsers

---

packages/porter/src/porter.js
packages/porter/test/integration/porter.test.js

before this change, there was this bug:
1. given dependency graph like home.js -> foo.css
2. two bundles will be created, one for home.js, one for the css extracted from home.js, namely, home.css
3. when user creates the actual home.css source file, the bundle of home.css didn't update

fix: always try to reload bundle in case new module were added

---

packages/demo-app/browser_modules/dynamic-import/bar.js
packages/demo-app/browser_modules/dynamic-import/foo.js
packages/demo-app/browser_modules/dynamic-import/suite.js
packages/porter/loader.js
packages/porter/src/bundle.js
packages/porter/src/module.js
packages/porter/src/packet.js
packages/porter/test/unit/bundle.test.js
packages/porter/test/unit/module.test.js
packages/porter/test/unit/packet.test.js

- foo.js -> import(bar.js) -> import './baz.css'
- generates three bundles
- foo.js
- bar.js
- bar.css -> baz.css
css dependencies brought by bar.js will be bundled together into bar.css, and requested automatically by the loader when calling `import(bar.js)`

fix: bundle css dependencies brought by dynamic imports

---

packages/porter/src/packet.js

fix: isolated packet should always be manifested

---

packages/porter/src/bundle.js
packages/porter/test/unit/compile_all.test.js

if source root were set to '/' and sources were something like `porter:///foo.js`, safari will turn the source into `/porter:///foo.js` which then generates too much level of directories in safari developer tools' sources tab

fix: no need to set source root when options.source.inline is positive

---

packages/porter/package.json
packages/porter/src/at_import.js
packages/porter/src/css_module.js
packages/porter/src/porter.js
packages/porter/test/complex/index.test.js
packages/porter/test/unit/at_import.test.js
packages/porter/test/unit/compile_all.test.js

parcel css currently generates nesting rules with `:is()` psaudo class, which is not working in chrome < 88 and hence does not strictly follow options.targets setting

fix: revert to postcss if not css modules

---

packages/porter/loader.js

fix: loader.js should be legacy browser tolerant

---

packages/porter/loader.js

loader.js isn't processed with babel or any other transpilers yet

fix: replace arrow function in loader.js with regular one

---

packages/demo-app/browser_modules/loader/suite.js
packages/demo-app/browser_modules/test/suite.js
packages/porter/loader.js
packages/porter/src/bundle.js

take following three entries for example
- entry/a.js -> import('./b.js') or import('./c.js') 
- entry/b.js -> overrides porter.lock because itself is a root entry and might have its own dependencies that needs to be mapped
- entry/c.js ->  overrides porter.lock because itself is a root entry and might have its own dependencies that needs to be mapped
when entry/a.js -> import('./b.js') happen, the manifest `porter.lock[pkg.name][pkg.version].manifest` will be overridden by the `Object.assign(porter.lock, {...})` in entry/b.js
This pr changes this behavior to a customized `porter.merge(target, source)`, which merges objects at arbitrary depth.

fix: porter.lock should be updated incrementally

---

packages/porter/src/module.js
packages/porter/test/complex/index.test.js

fix: module ids with jsx|tsx extensions should always be converted to js

---

packages/porter/src/bundle.js
packages/porter/test/integration/porter.test.js
packages/porter/test/unit/compile_all.test.js

not matter the entries are `['home.js', 'home.css']` or `['home.css', 'home.js']`

fix: compile either css entries orders shall yield with same result

---

packages/demo-typescript/.babelrc
packages/demo-typescript/components/about.tsx
packages/demo-typescript/package.json
packages/demo-typescript/test/.eslintrc
packages/demo-typescript/test/babel.test.js
packages/porter/src/porter.js
packages/porter/src/ts_module.js
packages/porter/test/typescript/index.test.js

```js
new Porter({
typescript: { compiler: 'babel' },  // default is 'tsc'
});
```
then typescript modules will be compiled with the babel config found at project root instead.

feat: transpile typescript code with babel

---

examples/app/browser_modules/test/suite.js
examples/app/browser_modules/test/worker.js
packages/porter/loader.js
packages/porter/src/bundle.js
packages/porter/src/module.js
packages/porter/test/unit/bundle.test.js
packages/porter/test/unit/match_require.test.js

also support worker syntax of vite:
```js
import Worker from './worker.js?worker';
```

fix: worker entries in root packet should present in module manifest

---

examples/app/browser_modules/test/suite.js
examples/app/package.json
examples/app/test/index.test.js
examples/typescript/test/tsc.test.js
packages/porter/src/packet.js

```js
"jquery": "^3.3.1",
"jquery2": "npm:jquery@^2.2.4",
```
- https://docs.npmjs.com/cli/v9/commands/npm-install

fix: handle package alias properly

---

packages/porter/loader.js
packages/porter/src/js_module.js
packages/porter/src/json_module.js
packages/porter/test/unit/compile_all.test.js

module systems at the AMD era commonly use `window.define()` to transport cjs modules into browser ready, such as https://github.com/modulex/modulex , https://github.com/seajs/seajs , or https://github.com/kissyteam/kissy
it is unnecessary to following this convention nowadays, it is intended that the pack result should be more enclosed.

chore: deprecate window.define(id, deps, factory)

---

packages/porter/src/porter.ts

fix: both {lock, package} are optional in PorterOptions
